cloudPlayer/urls.py
from django.contrib import admin
from django.urls import include,path

 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls')),
]

music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
	#/music/
   path('', views.IndexView.as_view(), name='index'),

    #/music/{album_id}/
    path('detail/<str:pk>/', views.DetailView.as_view(), name='detail'),

    #/music/album/add
    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),

]

music/models.py
from __future__ import unicode_literals

from django.db import models



class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)

	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk':self.pk})

	def __str__(self):
		return self.album_title + ' - ' + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album


class IndexView(generic.ListView):
	template_name = 'music/index.html'
	context_object_name = 'all_albums'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/detail.html'

class AlbumCreate(CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

music/templates/music/base.html
{% load static %}
{% block title %}
	<title>Star Tunes | Star Wars Music Player</title>
	<!--loads the path to static files such as stylesheets and/or scripts-->
	<!-- Materialize CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.2/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	{% endblock %}
	<!--Start of NavBar-->
	{% block body %}
	<nav id="layOut">
	    <div class="nav-wrapper container">

	      <a href="{% url 'music:index' %}" class="brand-logo center hide-on-med-and-down" id="layOut"><i class="fa fa-rebel" id="fontAwIcon" aria-hidden="true"></i>Star Tunes</a>
	      <a href="{% url 'music:index' %}" class="brand-logo center hide-on-large-only show-on-medium-and-down" id="layOut"><i class="fa fa-rebel" id="fontAwIcon" aria-hidden="true"></i>ST</a>
	      <a href="#" data-target="mobile-demo" class="sidenav-trigger left" id="layOut"><i class="material-icons">menu</i></a>
	      <a href="#" data-target="mobile-demo" class="sidenav-trigger show-on-large hide-on-med-and-down right" id="layOut"><i class="material-icons">menu</i></a>
	      <form class="left hide-on-med-and-down">
	        <div class="input-field">
	          <input id="search" type="search" required>
	          <label class="label-icon" for="search"><i class="material-icons">search</i></label>
	          <i class="material-icons">close</i>
	        </div>
	      </form>
	      <ul class="sidenav" id="mobile-demo">
	        <li><a href="{% url 'music:index' %}" id="layOut"><i class="material-icons">album</i>Albums</a></li>
	        <li><a href="#" id="layOut"><i class="material-icons">music_note</i>Songs</a></li>
	        <li><a href="#" id="layOut"><i class="material-icons">add</i>Add Album</a></li>
	        <li><a href="#" id="layOut"><i class="material-icons">power_settings_new</i>Log Out</a></li>
	      </ul>
	    </div>
	  </nav>
	  <main class="container">
	  	Dynamic content blocks from throughout the site
		</main>
	<div class="hide-on-large-only">
	<h4 class="center">Search For a Song/Album</h4>
	  	<br>
	  	<form>
	        <div class="input-field">
	          <input class="mobileSearch" id="search" type="search" required>
	          <label class="label-icon" for="search"><i class="material-icons">search</i></label>
	          <i class="material-icons">close</i>
	        </div>
	      </form>
	</div>
	{% endblock %}
	<!-- UIkit JS -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.2/js/materialize.min.js"></script>
	<script type="text/javascript" src="{% static 'music/init.js' %}"></script>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block body %}
<br>
<div class="row">
	<div class="col s12 m6 offset-m3 l4">
	      <div class="card">
	        <div class="card-image">
	          <img src="{{ album.album_logo }}" alt="{{ album.album_title }}, by {{ album.artist }}">
	        </div>
	        <div class="card-content">
	        	<ul class="collapsible">
    				<li class="active">
    					<div class="collapsible-header">
	        		<span class="card-title truncate">{{ album.album_title }}</span>
	        			</div>
	        			<div class="collapsible-body">
	        			<span class="card-title">{{ album.album_title }}</span>
	        			</div>
	        		</li>
	        		<li>Artist: {{ album.artist }}</li>
	        		<li>Genre: {{ album.genre }}</li>
	        	</ul>
	        	<!--
	        	<br>
	        	<p>Artist: {{ album.artist }}</p>
	        	<p>Genre: {{ album.genre }}</p>
	        	-->
	        </div>
	      </div>
	      
    </div>
<!--
<img src="{{ album.album_logo }}" alt="{{ album.album_title }}, by {{ album.artist }}">

<h3>{{ album.album_title }}</h3>
<h4>{{ album.artist }}</h4>
-->
<!--
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}
-->
	<div class="col s12 m12 l8">
	<div class="row">
		<a href="#" class="waves-effect waves-light btn"><i class="material-icons">add</i>Add Song</a>
		<a href="#" class="waves-effect waves-light btn">View All</a>
	</div>
	<table class="responsive highlight bordered">
		<thead>
			<th>Song Title</th>
            <th>Audio File</th>
            <th>Is a Favorite?</th>
            <th>Actions?</th>
		</thead>
		<tbody>
			{% for song in album.song_set.all %}
			<tr>
				<td>{{ song.song_title }}</td>
				<td>{{ song.file_type }}</td>
				<td>{% if song.is_favorite %}
				<img src="http://icons.iconarchive.com/icons/3xhumed/star-wars-the-old-republic/16/Star-Wars-The-Old-Republic-8-icon.png" alt="This is a favorite song" />
			{% endif %}</td>
				<td></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<!--
{% for song in album.song_set.all %}
		<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
		<label for="song{{ forloop.counter }}">
			{{ song.song_title }}
			{% if song.is_favorite %}
				<img src="http://icons.iconarchive.com/icons/3xhumed/star-wars-the-old-republic/16/Star-Wars-The-Old-Republic-8-icon.png" alt="This is a favorite song" />
			{% endif %}
		</label>
		<br>
	{% endfor %}
	-->
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
	
	<!--if statement if there are no albums-->
	<h3>Here are all of the Albums:</h3>
	<!--{% if all_albums %}-->
	<!--
	<ul>
		{% for album in all_albums %}
		<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
		{% endfor %}
	</ul>
	-->

	<div class="row">
    	{% for album in all_albums %}
    	<div class="col s12 m6 l4">
    		
	      <div class="card">
	        <div class="card-image">
	          <img src="{{ album.album_logo }}" alt="{{ album.album_title }}, by {{ album.artist }}">
	        </div>
	        <div class="card-content">
	        	<span class="card-title truncate">{{ album.album_title }}</span>
	        	<p>{{ album.artist }}</p>
	          	<br>
	          	<div class="row">
	          	<a href="{% url 'music:detail' album.id %}" class="waves-effect waves-light btn" title="View ALbum Details">Details</a>

	          	<a class="waves-effect waves-light btn" title="Add to Favorites"><i class="material-icons">add_circle_outline</i></a>

	          	<a class="waves-effect waves-light btn" title="Delete Album"><i class="material-icons">delete</i></a>
	          	</div>

	        </div>
	      </div>
	      
    	</div>
    	{% endfor %}
  </div>
	<!--
	{% else %}
		<h2>You don't have any albums</h2>
	{% endif %}
	-->
{% endblock %}